version: '2.1'

services:
  auth:
    restart: always
    build: auth/
    volumes:
      - ./auth/ :/auth/
    expose:
      - "13451"
  quotation:
    restart: always
    build: cote/
    volumes:
      - ./cote/ :/cote/
    expose:
      - "13452"